Work about section
MindPrepDev/Persona-Portfolio pull request #2
Opened 2022-05-25 17:09 UTC by MindPrepDev

2022-05-25 17:34 UTC, youmari requested changes
Hi @MindPrepDev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ No linter error 
✔️ Great title and  short summary 
✔️ Github flow 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 17:34 UTC, youmari commented on index.html
> +          <h3 class="hype-pro sub-pro">Multi-Post Stories</h3>
- [ ] it would be better if you stick to the Figma design and change the background color of this section to `White ` as the Figma design in order to match the design

2022-05-25 17:34 UTC, youmari commented on index.html
> +      </div>
- [ ] [OPIONTAL] instead of `<div>` tag try to use `<article>` tag that will improve your SEO benchmark and also article is great for your case always try to use the right semantic tags as much as possible instead of `<div>` tag

2022-05-25 17:34 UTC, youmari commented on index.html
> +          <input type="button" value="See Project">
- [ ] it would be better if you use `<a>` tag or `<button>` instead of `<input>` as I told you above always try to use the right semantic tags as much as possible so I encourage you to do that

2022-05-25 17:53 UTC, MindPrepDev commented on index.html
> +          <h3 class="hype-pro sub-pro">Multi-Post Stories</h3>
Thanks man, I appreciate. It's good to have you watch my back again. Have you checked the template itself? The background color is not white although it looks white. Did was in fact pointed out to me by another code reviewer before I had to repeat the module. Please let me know your final verdict before I effect this correction. Thanks again, boss.

2022-05-25 17:54 UTC, MindPrepDev commented on index.html
> +          <h3 class="hype-pro sub-pro">Multi-Post Stories</h3>
> * [ ]  it would be better if you stick to the Figma design and change the background color of this section to `White ` as the Figma design in order to match the design

Thanks man, I appreciate. It's good to have you watch my back again. Have you checked the template itself? The background color is not white although it looks white. Did was in fact pointed out to me by another code reviewer before I had to repeat the module. Please let me know your final verdict before I effect this correction. Thanks again, boss.

2022-05-26 06:39 UTC, MindPrepDev commented on index.html
> +          <h3 class="hype-pro sub-pro">Multi-Post Stories</h3>
Alright, thanks for your understanding.

2022-05-26 06:41 UTC, MindPrepDev commented on index.html
> +      </div>
I used flexbox for the <ul> container and think display: grid would be perfect for the works-section because of the desktop version. Is it okay?

2022-05-26 07:07 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @MindPrepDev, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 07:33 UTC, merged