Setup local storage
MindPrepDev/Persona-Portfolio pull request #26
Opened 2022-06-24 11:52 UTC by MindPrepDev

This branch adds local storage functionality to the portfolio site to enhance accessibility and improve user experience.
How it achieves this feat is by:

- Preventing default form behaviour i.e submission before capturing user's input
- Checking for any past interactivity between the user and the platform and dynamically upload the inputs found
- If not found, it then goes on to set new inputs into the storage
- Lastly, it submits the form

2022-06-24 12:02 UTC, roshan-bajgain requested changes
Hi @MindPrepDev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 12:02 UTC, roshan-bajgain commented on main.js
> +    }
- [ ] After filling out the form, and not submitting it, the entered values should be saved in the local storage. kindly implement it as it is not saving
### Image
![ss](https://user-images.githubusercontent.com/81727988/175530078-993484ad-fe3a-4259-bba1-18dfb28496b9.png)

2022-06-24 12:02 UTC, roshan-bajgain commented on main.js
> +      localStorage.setItem('userInfo', JSON.stringify(userData));
- [ ] When the user loads the page if there is any data in the local storage the input fields are pre-filled with this data. kindly implement it as well

2022-06-25 13:46 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @MindPrepDev @roshan-bajgain 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-25 13:49 UTC, merged